- python
    - python is a programming paradism means it supports functional programming and object oriented programming and also works with procedure oriented programming
- procedure oriented language
    - procedure oriented means write our programming language using fuctions and classes
 - object oriented language
     - object-is areal world entity
     - class:logical entity contains logic of the application

In [1]:
# syntax::
class class_name:
    variables
    methods or function

In [2]:
print("hii")

hii


In [3]:
5+78

83

In [4]:
class Hi:
    a=60
    b=56
    name="cse"
    def show():
        print("iam from show() function")
    

In [5]:
Hi.a

60

In [6]:
Hi.b

56

In [7]:
Hi.show()

iam from show() function


In [8]:
Hi.name

'cse'

In [9]:
class Hi:
    name="moblie"
    program_name='python'
    def display():
        print("iam fron display function()")
    def show():
        print("iam from show()")
print(Hi.name,Hi.program_name)
print(Hi.display())

moblie python
iam fron display function()
None


In [11]:
Hi.show()

iam from show()


In [12]:
class Hello:
    name="moblie"
    def display():
        print("iam fron display function()")
        return("iam from return statements")
    def show():
        print("iam from show()")
print(Hello.display())
print(Hello.show())

iam fron display function()
iam from return statements
iam from show()
None


In [ ]:
# in java object declaration
    # class_name obj_name=new class-name
# python
    # obj_name=class_name

In [14]:
class Hi:
    name="moblie"
    program_name='python'
    def display(self):
        print("iam fron display function()")
        return(" iam return staements")
    def show():
        print("iam from show()")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

moblie python
iam fron display function()
 iam return staements


### constructor
- constructor without using object we will call methods
    - in java:: class name should be same as method name
    - in python: we will use one special method to define constructor
    - __init(self)__

In [15]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hii",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('valli','21A85A0518')
obj.display()

hii valli
your roll_no 21A85A0518


### inheritance
- inherits something from parent class to child class

In [ ]:
class A:
    #a,b=30,c=70
class B(A):
    #c,d=40,50

In [17]:
class A:
    a,b=20,40
    def msg():
        print(" iam from class A")
class B(A):
    c,d=67,76
    def msg1():
        print("iam from class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

67 20
iam from class B
 iam from class A


## python libararies for data science
- organizing,processing,analyzing the huge amount data
- apply data visualization
- extracting the data from the source
- nearly 20 python libararies are there


## top
- numpy
- pandas
- matplotlib

## numpy
- numpy::(num+py) means numerical data+ python
- it is fundamental package for scientific computing in python
- numpy is python libarary
- it is used to create mulit-dimensional arrays for fast opearations
    - its dealing with mathematical scientific staticial data
    - numpy cointains a powerful n-dimentional array object which in the form
    - we can initialise numpy arrays from nested python lists

In [ ]:
# how to install numpy
- pip install numpy

In [19]:
# how to import and use numpy package
import numpy as np

In [20]:
## how to find the numpy version
np.__version__

'1.20.3'

In [21]:
## how to create numpy array
import numpy as np
a=np.array([1,2,3,4]) # single dimensional array
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [23]:
a2=np.array([[2,3,4],[5,7,8]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 7 8]]
<class 'numpy.ndarray'>


In [24]:
# to know about the shape of the array
a2.shape

(2, 3)

In [25]:
li=[4,6,8,'h','j']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['4' '6' '8' 'h' 'j']
<class 'numpy.ndarray'>


In [26]:
b=np.array([[2,3],[6,7]])
print(b)

[[2 3]
 [6 7]]


In [28]:
print(ar.btype)

NameError: name 'ar' is not defined

In [30]:
ar=np.array([[4,5],[7,8],[9,3]])
ar

array([[4, 5],
       [7, 8],
       [9, 3]])

In [32]:
print(ar.dtype)

int32


In [33]:
print(b.shape)

(2, 2)


In [34]:
b.itemsize

4

In [35]:
b.ndim

2

In [36]:
# range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(2,4,6))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[2]
1


In [38]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [39]:
# arange()- third party of numpy libarary
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
y=np.arange(10)
print(y.reshape(5,2))



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [45]:
# reshape of array
a1=np.array([1,2,3,4,5,6])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(3,2)
print("after reshape",a2)
print(a2.reshape)
print(a2.ndim)

(6,)
before reshape [1 2 3 4 5 6]
1
after reshape [[1 2]
 [3 4]
 [5 6]]
<built-in method reshape of numpy.ndarray object at 0x00000023D996F630>
2


In [46]:
## resize of array its modifies shape amd array itself
a1=np.array([1,2,3,4,5,6,7])
print(a1)
print(a1.shape)
a1.resize(3)
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7]
(7,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [49]:
# zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [51]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [102]:
# full array full
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [54]:
np.diag(a)

array([7, 7, 7])

In [55]:
np.full(3,100)

array([100, 100, 100])

In [57]:
np.full((3,9),100)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [60]:
# eye array
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [66]:
r=np.random.randint(1,10)
r

9

In [68]:
t=np.random.randint(1,16,12).reshape(3,4)
t

array([[ 6, 14,  1, 15],
       [ 9,  1, 13,  7],
       [ 8, 11,  3,  6]])

In [70]:
q=np.random.random((6)).reshape(2,3)
q

array([[0.03878688, 0.32536455, 0.5391722 ],
       [0.56257729, 0.4039344 , 0.54379603]])

In [75]:
r=np.random.randint(1,10,(5,3))
r

array([[1, 2, 6],
       [6, 7, 5],
       [8, 1, 5],
       [8, 8, 2],
       [4, 4, 9]])

In [79]:
r[1:5]

array([[6, 7, 5],
       [8, 1, 5],
       [8, 8, 2],
       [4, 4, 9]])

In [78]:
r[2:,:2]

array([[8, 1],
       [8, 8],
       [4, 4]])

In [88]:
r[r>10].sum()

0

In [83]:
r.max()

9

In [82]:
r.min()

1

In [85]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
print(a+b)
print("***********")
print(a-b)
print("----------")
print(a*b)
print("$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
***********
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
----------
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
$$$$$$$$
[[0 1 0]
 [1 0 1]
 [0 1 0]]
8
2


In [92]:
# 0-15--->(3,5)
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [93]:
print(np.mean(a))

7.0


In [94]:
print(np.median(a))

7.0


In [103]:
q.dot(a)

array([[ 6.32326538,  6.32326538,  6.32326538],
       [10.57215404, 10.57215404, 10.57215404]])

In [96]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [97]:
a+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [98]:
a+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [99]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [104]:
np.exp(4)

54.598150033144236

In [105]:
np.sin(30)

-0.9880316240928618

In [106]:
np.cos(30)

0.15425144988758405

In [107]:
np.tan(30)

-6.405331196646276

import numpy
dir(numpy)

## pandas
- pandas is the data science package 
- it is used for 
     - data manupulation(modifications and updation)
     - data analysis
     - data cleaning- to remove unnecessary data from data science
- contains mainly 2 data structures in pandas
    - series- sequence of data
    - data frames- data with row and column
